[tool.poetry]
name = "rag"
version = "0.1.0"
description = ""
authors = ["mattecasu <mattecasu@gmail.com>"]
readme = "README.md"
packages = [{ include = "rag" }]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
langchain = "^0.1.12"
chromadb = "^0.4.24"
pypdf = "^4.1.0"
langchainhub = "^0.1.15"
transformers = "^4.38.2"
pytest = "^8.1.1"
sentence-transformers = "^2.5.1"
ragatouille = "^0.0.7.post10"
srsly = "^2.4.8"
streamlit = "^1.32.2"
docx2txt = "^0.8"
unstructured = {extras = ["all-docs"], version = "^0.12.5"}
python-docx = "^1.1.0"
watchdog = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
